# Generated by Django 2.2.6 on 2022-03-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220324_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите картинку для поста', null=True, upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
